# Generated by Django 5.0.3 on 2024-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_attendees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
